import React, { useState } from "react";
import "./GameGenerator.css";
import { generateGameIdea } from "./GameLogic";
import { useHistory } from "react-router-dom";
import Sidebar from "../../components/Sidebar/Sidebar";

const GameGenerator = () => {
  const [interest1, setInterest1] = useState("");
  const [interest2, setInterest2] = useState("");
  const [subject, setSubject] = useState("");
  const [result, setResult] = useState(null);
  const [xp, setXp] = useState(0);
  const [badges, setBadges] = useState([]);
  const history = useHistory();

  const handleGenerate = () => {
    const idea = generateGameIdea(interest1, interest2, subject);
    setResult(idea);

    const earnedXP = subject.length + interest1.length + interest2.length;
    setXp((prev) => prev + Math.min(earnedXP, 50));

    if (idea.badge && !badges.includes(idea.badge)) {
      setBadges([...badges, idea.badge]);
    }

    if (idea.route) {
      setTimeout(() => history.push(idea.route), 3000); // v5 syntax
    }
  };

  return (
    <div className="generator-container">
      <Sidebar />
      <div className="generator">
        <h2>🎮 Game Generator</h2>
        <p>Describe your interests and the topic you want to learn about:</p>

        <div className="inputs">
          <div className="input-group">
            <label>Interest #1: </label>
            <input
              type="text"
              placeholder="e.g. Cars"
              value={interest1}
              onChange={(e) => setInterest1(e.target.value)}
            />
          </div>

          <div className="input-group">
            <label>Interest #2: </label>
            <input
              type="text"
              placeholder="e.g. Dogs"
              value={interest2}
              onChange={(e) => setInterest2(e.target.value)}
            />
          </div>

          <div className="input-group">
            <label>Subject: </label>

            <input
              type="text"
              placeholder="e.g. Photosynthesis"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
            />
          </div>

          <button onClick={handleGenerate}>🔍 Generate Game</button>
        </div>

        <div className="xp-bar-wrap">
          <div className="xp-bar" style={{ width: `${xp}%` }}></div>
          <p>XP: {xp}</p>
        </div>

        <div className="badges">
          {badges.map((badge, i) => (
            <span key={i} className="badge">
              🏅 {badge}
            </span>
          ))}
        </div>

        {result && (
          <div className="result-card">
            <h3>{result.title}</h3>
            <p>{result.description}</p>
            {result.image && (
              <img src={result.image} alt="preview" className="game-image" />
            )}
            <p className="ai-label">🤖 Generated by AI</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default GameGenerator;
